@startuml
'https://plantuml.com/sequence-diagram

title 找回密码逻辑
skinparam BoxPadding 40
autonumber "<font color=red><b>"
actor 用户 as User
activate User

User -> Web: 点击找回密码
activate Web
    Web --> User: 返回找回密码页面
    deactivate Web
group #fefcfa 校验邮箱
    User->User: 输入邮箱
    User->Web: 点击发送验证码
        activate Web
        Web->Api: 调用发送验证码接口(参数operate_id, email)
            activate Api
            group #a0c0f033 发送邮箱验证码逻辑
                Api->Api: 校验邮箱地址是否存在
                Api->Api: 发送邮箱验证码
                Api->Api: 保存邮箱验证码
            end
            Api-->Web: 验证码发送成功
            deactivate Api
        Web-->User: 验证码发送成功
        deactivate Web
    User->User: 输入收到的邮箱验证码
    User->Web: 点击验证邮箱
        activate Web
        Web->Api: 调用验证邮箱接口(参数operate_id, email_code)
            activate Api
            Api->Api: 从缓存中取出邮箱验证码
            Api->Api: 校验验证码
            Api->Api: 校验成功保存邮箱信息
            Api-->Web: 返回验证结果
            deactivate Api
        Web-->User: 返回验证结果, 弹窗提示输入新密码
        deactivate Web
end
group #fafafa 重置密码
    User->User: 输入新密码两次
    User-->Web: 点击确定按钮
        activate Web
        Web->Web: 校验两次密码是否一致
        Web->Api: 获取公钥(参数operate_id)
            activate Api
            Api->Api: 生成密钥对
            Api->Api: 根据operate_id保存私钥
            Api-->Web: 返回公钥
            deactivate Api
        Web->Web: 加密密码
        Web->Api: 调用修改密码接口(参数operate_id, password(加密后的))
            group #ffefff 重置密码逻辑
                activate Api
                Api->Api: 校验邮箱是否已验证
                Api->Api: 解密密码
                Api->Api: 校验密码格式
                Api->Api: hash密码并更新
                Api-->Web: 返回更新成功
                deactivate Api
            end
        Web-->User: 返回密码更新成功, 并跳转到登录页面
        deactivate Web
end
@enduml